// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Device struct {
	ID              interface{} `json:"id"`
	DeviceName      string      `json:"device_name"`
	Hostname        string      `json:"hostname"`
	LastPingLatency int64       `json:"last_ping_latency"`
	IsUp            bool        `json:"is_up"`
}
