// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDevices = `-- name: CreateDevices :one
INSERT INTO devices(
  id, device_name, hostname
)
VALUES (?, ?, ?)
RETURNING id, device_name, hostname, last_ping_latency, is_up, failed_pings, alerted_down
`

type CreateDevicesParams struct {
	ID         uuid.UUID `json:"id"`
	DeviceName string    `json:"device_name"`
	Hostname   string    `json:"hostname"`
}

func (q *Queries) CreateDevices(ctx context.Context, arg CreateDevicesParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevices, arg.ID, arg.DeviceName, arg.Hostname)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.Hostname,
		&i.LastPingLatency,
		&i.IsUp,
		&i.FailedPings,
		&i.AlertedDown,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices
WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDevice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDevices = `-- name: GetDevices :many
SELECT id, device_name, hostname, last_ping_latency, is_up, failed_pings, alerted_down FROM devices
`

func (q *Queries) GetDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceName,
			&i.Hostname,
			&i.LastPingLatency,
			&i.IsUp,
			&i.FailedPings,
			&i.AlertedDown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceStateAndLatency = `-- name: SetDeviceStateAndLatency :one
UPDATE devices
SET is_up = ?, last_ping_latency = ?, failed_pings = ?, alerted_down = ?
WHERE id = ?
RETURNING id, device_name, hostname, last_ping_latency, is_up, failed_pings, alerted_down
`

type SetDeviceStateAndLatencyParams struct {
	IsUp            bool      `json:"is_up"`
	LastPingLatency int64     `json:"last_ping_latency"`
	FailedPings     int64     `json:"failed_pings"`
	AlertedDown     bool      `json:"alerted_down"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) SetDeviceStateAndLatency(ctx context.Context, arg SetDeviceStateAndLatencyParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, setDeviceStateAndLatency,
		arg.IsUp,
		arg.LastPingLatency,
		arg.FailedPings,
		arg.AlertedDown,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.Hostname,
		&i.LastPingLatency,
		&i.IsUp,
		&i.FailedPings,
		&i.AlertedDown,
	)
	return i, err
}

const updateDevices = `-- name: UpdateDevices :one
UPDATE devices
SET device_name = ?, hostname = ?
WHERE id = ?
RETURNING id, device_name, hostname, last_ping_latency, is_up, failed_pings, alerted_down
`

type UpdateDevicesParams struct {
	DeviceName string    `json:"device_name"`
	Hostname   string    `json:"hostname"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDevices(ctx context.Context, arg UpdateDevicesParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, updateDevices, arg.DeviceName, arg.Hostname, arg.ID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.Hostname,
		&i.LastPingLatency,
		&i.IsUp,
		&i.FailedPings,
		&i.AlertedDown,
	)
	return i, err
}
